services:
  db:
    image: ankane/pgvector
    container_name: jarvis_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jarvis
      POSTGRES_PASSWORD: jarvispassword
      POSTGRES_DB: jarvis_memory
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

