"""Add user_id to memories

Revision ID: 8827b0169f6c
Revises: 90d0d5ff6e3e
Create Date: 2025-04-26 18:44:48.034325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8827b0169f6c'
down_revision: Union[str, None] = '90d0d5ff6e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('user_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'user_id')
    # ### end Alembic commands ###
